"""Spaced Repetition Deck Exporter.

Supports exporting Pitagora review decks to standard Anki TSV and Obsidian Markdown formats.
"""

from __future__ import annotations

import csv
import os
from typing import Any

from sqlite_utils import Database
from pitagora.core.constants import MEMORY_DB
from pitagora.memory.store import MemoryStore


def export_deck_to_anki(output_path: str, db_path: str = str(MEMORY_DB)) -> int:
    """Exports spaced review items and misconceptions to an Anki-compatible TSV file."""
    output_path = os.path.expanduser(output_path)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    db = Database(os.path.expanduser(db_path))
    cards: list[tuple[str, str, str]] = []

    # 1. From spaced_reviews
    if db["spaced_reviews"].exists():
        for row in db["spaced_reviews"].rows:
            concept = row.get("concept", "")
            interval = row.get("interval", 0)
            ease = row.get("ease_factor", 2.5)
            front = f"Pitagora Concept: {concept}"
            back = f"Review interval: {interval}d (Ease: {ease:.2f}). Recall first principles & formal definition."
            cards.append((front, back, "Pitagora::SpacedRepetition"))

    # 2. From misconceptions
    mem = MemoryStore(db_path=db_path)
    misconceptions = mem.get_misconceptions(unresolved_only=False)
    for m in misconceptions:
        front = f"Misconception Check: {m['concept']}"
        back = f"<b>Flawed intuition:</b> {m['misconception']}<br><br><b>Correction:</b> {m.get('resolution') or 'Review core principles'}"
        cards.append((front, back, "Pitagora::Misconceptions"))

    with open(output_path, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f, delimiter="	")
        for front, back, tag in cards:
            writer.writerow([front, back, tag])

    return len(cards)


def export_deck_to_markdown(output_path: str, db_path: str = str(MEMORY_DB)) -> int:
    """Exports spaced review items to an Obsidian-compatible flashcard markdown file."""
    output_path = os.path.expanduser(output_path)
    os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)

    db = Database(os.path.expanduser(db_path))
    lines = [
        "# Pitagora Spaced Repetition Deck",
        "",
        "> Generated by Pitagora. Compatible with Obsidian Spaced Repetition plugin.",
        "",
    ]
    card_count = 0

    if db["spaced_reviews"].exists():
        lines.append("## Concepts Due & Active Review")
        lines.append("")
        for row in db["spaced_reviews"].rows:
            concept = row.get("concept", "")
            interval = row.get("interval", 0)
            lines.append(f"### {concept} #flashcard")
            lines.append(f"Explain the foundational derivation and physical/mathematical intuition for **{concept}**.")
            lines.append("?")
            lines.append(f"Target mastery maintained at interval {interval} days.")
            lines.append("")
            card_count += 1

    mem = MemoryStore(db_path=db_path)
    misconceptions = mem.get_misconceptions(unresolved_only=False)
    if misconceptions:
        lines.append("## Conceptual Pitfalls & Misconceptions")
        lines.append("")
        for m in misconceptions:
            lines.append(f"### Misconception in {m['concept']} #flashcard")
            lines.append(f"What common error occurs regarding **{m['concept']}**?")
            lines.append("?")
            lines.append(f"**Pitfall:** {m['misconception']}")
            if m.get("resolution"):
                lines.append(f"**Resolution:** {m['resolution']}")
            lines.append("")
            card_count += 1

    with open(output_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    return card_count
